#!/usr/bin/env node
// Rebuild the gateway's SNI -> origin map from the registry.
//
// Written to a temp file and renamed into place, so a reload that races the
// generator reads either the old map or the new one and never a half-written
// file. nginx is only reloaded when the contents actually changed — this is
// meant to be run from a timer, and a reload every minute for no reason
// drops long-lived connections for no reason.
//
// Registry contract:
//   GET {base}/api/moshpit/names
//     200 -> { "names": [ { "name": "foo.moshpit", "target": "203.0.113.4:443" } ] }
//
// MOSHPIT_UPSTREAMS_SOURCE can point at a local JSON file of the same shape
// instead, which is how a private grid runs this without a registry at all.

import { readFile, rename, writeFile } from "node:fs/promises";
import { execFile } from "node:child_process";
import { promisify } from "node:util";

const run = promisify(execFile);

const base = (process.env.MOSHPIT_REGISTRY_BASE || "https://pit.moshcode.sh").replace(/\/+$/, "");
const output = process.env.MOSHPIT_UPSTREAMS_MAP || "/etc/nginx/moshpit-upstreams.map";
const source = process.env.MOSHPIT_UPSTREAMS_SOURCE;
const reload = process.env.MOSHPIT_UPSTREAMS_RELOAD !== "0";

type Entry = { name?: unknown; target?: unknown };

const payload: { names?: Entry[] } = source
  ? JSON.parse(await readFile(source, "utf8"))
  : await (await fetch(`${base}/api/moshpit/names`, { headers: { accept: "application/json" } })).json();

const lines: string[] = [];
let skipped = 0;

for (const entry of payload.names ?? []) {
  const name = typeof entry.name === "string" ? entry.name.trim().toLowerCase() : "";
  const target = typeof entry.target === "string" ? entry.target.trim() : "";

  // Anything that could inject a directive is dropped rather than escaped.
  // This file is included into an nginx map block; being strict about what may
  // enter it is cheaper than being clever about quoting.
  if (!/^[a-z0-9.-]+$/.test(name) || !/^[a-z0-9.:\[\]-]+$/i.test(target) || !target.includes(":")) {
    skipped++;
    continue;
  }
  lines.push(`    ${name}  ${target};`);
}

lines.sort();
const body = `# Generated by gen-upstreams.ts. Do not edit.\n${lines.join("\n")}\n`;

const previous = await readFile(output, "utf8").catch(() => "");
const unchanged = stripHeader(previous) === stripHeader(body);

if (unchanged) {
  console.log(`[upstreams] ${lines.length} names, unchanged${skipped ? `, ${skipped} skipped` : ""}`);
  process.exit(0);
}

const temp = `${output}.tmp`;
await writeFile(temp, body, { mode: 0o644 });
await rename(temp, output);
console.log(`[upstreams] wrote ${lines.length} names to ${output}${skipped ? `, ${skipped} skipped` : ""}`);

if (reload) {
  // Config test first. A reload on a bad map takes the whole gateway's stream
  // block down, and the map is machine-generated from data we do not control.
  await run("nginx", ["-t"]);
  await run("nginx", ["-s", "reload"]);
  console.log("[upstreams] nginx reloaded");
}

function stripHeader(text: string): string {
  return text.split("\n").filter((line) => !line.startsWith("#")).join("\n").trim();
}
